target: Attrition

numerical_features:
  - Age
  - DailyRate
  - DistanceFromHome
  - HourlyRate
  - MonthlyIncome
  - MonthlyRate
  - NumCompaniesWorked
  - PercentSalaryHike
  - TotalWorkingYears
  - TrainingTimesLastYear
  - YearsAtCompany
  - YearsInCurrentRole
  - YearsSinceLastPromotion
  - YearsWithCurrManager

categorical_features:
  - BusinessTravel
  - Department
  - EducationField
  - Gender
  - JobRole
  - MaritalStatus
  - OverTime

ordinal_maps:
  Education:
    "Below College": 1
    "College": 2
    "Bachelor": 3
    "Master": 4
    "Doctor": 5

  EnvironmentSatisfaction:
    "Low": 1
    "Medium": 2
    "High": 3
    "Very High": 4

  JobInvolvement:
    "Low": 1
    "Medium": 2
    "High": 3
    "Very High": 4

  JobLevel:
    "1": 1
    "2": 2
    "3": 3
    "4": 4
    "5": 5

  JobSatisfaction:
    "Low": 1
    "Medium": 2
    "High": 3
    "Very High": 4

  PerformanceRating:
    "Low": 1
    "Good": 2
    "Excellent": 3
    "Outstanding": 4

  RelationshipSatisfaction:
    "Low": 1
    "Medium": 2
    "High": 3
    "Very High": 4

  StockOptionLevel:
    "0": 0
    "1": 1
    "2": 2
    "3": 3

  WorkLifeBalance:
    "Bad": 1
    "Good": 2
    "Better": 3
    "Best": 4

onehot_columns:
  - BusinessTravel
  - Department
  - EducationField
  - Gender
  - JobRole
  - MaritalStatus
  - OverTime

outlier_columns:
  - MonthlyIncome
  - TotalWorkingYears
  - YearsAtCompany
  - DistanceFromHome

engineered_features:
  - IncomePerYear
  - SatisfactionScore
  - LoyaltyIndex
  - WorkloadScore
  - CareerGrowthRate
  - OverTimeRisk
  - TenureStabilityIndex
  - OverTimeXSatisfaction
  - StagnationRisk
  - IncomeVsExperience
  - DistanceXOverTime