logistic_regression:
  search: "grid"
  cv: 3
  scoring: "f1_macro"
  param_grid:
    C:            [0.1, 1]
    penalty:      ["l2"]
    solver:       ["liblinear"]
    class_weight: ["balanced"]

random_forest:
  search: "random"
  cv: 3
  n_iter: 5
  scoring: "f1_macro"
  n_jobs: -1
  param_distributions:
    n_estimators:      [100, 200]
    max_depth:         [5, 10]
    min_samples_split: [5, 10]
    min_samples_leaf:  [2, 4]
    class_weight:      ["balanced"]

xgboost:
  search: "random"
  cv: 3
  n_iter: 5
  scoring: "f1_macro"
  n_jobs: -1
  param_distributions:
    n_estimators:     [100, 200]
    learning_rate:    [0.05, 0.1]
    max_depth:        [3, 5]
    subsample:        [0.7, 0.8]
    colsample_bytree: [0.7, 0.9]